---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-schedule-apigateway
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-schedule-apigateway
  template:
    metadata:
      labels:
        app: my-schedule-apigateway
    spec:
      containers:
        - image: myschedule.azurecr.io/my-schedule.apigateway:{IMAGE_TAG}
          name: my-schedule-apigateway
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0"
              memory: "0"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: myschedule
                    operator: In
                    values:
                      - "myschedule"
---
apiVersion: v1
kind: Service
metadata:
  name: my-schedule-apigateway
  namespace: default
spec:
  ports:
    - name: port80
      port: 80
  selector:
    app: my-schedule-apigateway
  type: LoadBalancer
