---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-schedule-authservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-schedule-authservice
  template:
    metadata:
      labels:
        app: my-schedule-authservice
    spec:
      containers:
        - image: myschedule.azurecr.io/my-schedule.authservice:{{ github.sha }}
          name: my-schedule-authservice
          env:
            - name: MessageQueueHostName
              # value: ${{ secrets.MESSAGEQUEUEHOSTNAME }}
              value: "rabbitmq-service"
            - name: MessageQueuePort
              value: "5672"
            - name: MessageQueueUserName
              value: "guest"
            - name: MessageQueuePassword
              value: "guest"
            - name: MessageQueueVirtualHost
              value: "/"
            - name: MessageQueueUseSsl
              value: "false"
            - name: MessageQueueHeaderName
              value: "ServiceName"
            - name: MessageQueueServiceName
              value: "AuthService"
          # envFrom:
          #   - configMapRef:
          #       name: my-schedule-authservice-config
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0"
              memory: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: my-schedule-authservice
  namespace: default
spec:
  ports:
    - name: port80
      port: 80
  selector:
    app: my-schedule-authservice
  type: ClusterIP
