---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-schedule-userservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-schedule-userservice
  template:
    metadata:
      labels:
        app: my-schedule-userservice
    spec:
      containers:
        - image: myschedule.azurecr.io/my-schedule.userservice:{{ github.sha }}
          name: my-schedule-userservice
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0"
              memory: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: my-schedule-userservice
  namespace: default
spec:
  ports:
    - name: port80
      port: 80
  selector:
    app: my-schedule-userservice
  type: ClusterIp
